export const ERR_LOGIN_401_MESSAGE = "Вы ввели неправильный логин или пароль.";
export const ERR_LOGIN_403_MESSAGE = "При авторизации произошла ошибка. Токен не передан или передан не в том формате.";
export const ERR_LOGIN_400_MESSAGE = "При авторизации произошла ошибка. Переданный токен некорректен.";
export const ERR_REG_409_MESSAGE = "Пользователь с таким email уже существует.";
export const ERR_REG_400_MESSAGE = "При регистрации пользователя произошла ошибка.";
export const ERR_PROFILE_409_MESSAGE = "Пользователь с таким email уже существует.";
export const ERR_PROFILE_400_MESSAGE = "При обновлении профиля произошла ошибка.";
export const ERR_500_MESSAGE = "На сервере произошла ошибка.";
export const ERR_404_MESSAGE = "Страница по указанному маршруту не найдена.";
export const ERR_MOVIES_500 = "Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз"